---
- hosts: all
  remote_user: root

  vars:
    local_user: "{{ lookup('env', 'USER') }}"

  vars_prompt:
  - name: user_password
    prompt: Enter password for your user
    private: yes
    encrypt: sha512_crypt
    confirm: yes
    salt_size: 7

  tasks:
    - name: Make group for local user
      group:
        name: "{{ local_user }}"
        state: present

    - name: Create local user
      user:
        name: "{{ local_user }}"
        shell: /bin/bash
        append: yes
        groups: sudo
        group: "{{ local_user }}"
        password: "{{ user_password }}"
        state: present

    - name: Add authorized_key for local user
      authorized_key:
        user: "{{ local_user }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Secure home directory
      file:
        path: "/home/{{ local_user }}/"
        state: touch
        owner: "{{local_user}}"
        group: "{{local_user}}"
        mode: '2750' # Without quotes: d-wSrwxrwT  with quotes:  drwxr-s---

    - name: Install acl
      apt:
        pkg: acl
        state: latest

    - name: Make permissions sticky
      shell: "getfacl --access /home/{{ local_user }}/ | setfacl -d -M- /home/{{ local_user }}/"
      sudo: yes

    - name: Copy dotfiles
      copy:
        src: "{{item}}"
        dest: "/home/{{ local_user }}/"
        owner: "{{local_user}}"
        group: "{{local_user}}"
        mode: '0640'
      with_fileglob:
        - ../dotfiles/.*