---
- hosts: all
  remote_user: root
  ask_pass: True
  ask_sudo_pass: False

  vars:
    local_user: "{{ lookup('env', 'USER') }}"

  vars_prompt:
  - name: user_password
    prompt: Enter password for your user
    private: yes
    encrypt: sha512_crypt
    confirm: yes
    salt_size: 7

  tasks:
    - name: Create local user
      user:
        name: "{{ local_user }}"
        shell: /bin/bash
        append: yes
        groups: sudo
        group: "{{ local_user }}"
        password: "{{ user_password }}"
        state: present

    - name: Add authorized_key for local user
      authorized_key:
        user: "{{ local_user }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Secure home directory
      file:
        path: "/home/{{ local_user }}/"
        state: directory
        owner: "{{local_user}}"
        group: "{{local_user}}"
        mode: 2750

    - name: Make permissions sticky
      command: "getfacl --access /home/{{ local_user }}/ | setfacl -d -M- /home/{{ local_user }}/"
      sudo: yes

    - name: Copy dotfiles
      copy:
        src: "{{item}}"
        dest: "/home/{{ local_user }}/"
        owner: "{{local_user}}"
        group: "{{local_user}}"
        mode: 0640
      with_fileglob:
        - ../dotfiles/.*