---
- hosts: all

# local ~/.chube should have:
#
# ---
# api_key: linode_api_key_here

  tasks:
  - include: linode_facts.yml
  # - include: apt.yml
  # - include: basics.yml
  # - include: newrelic.yml
  # - include: rvm.yml
  # - include: ruby.yml
  # - include: gems.yml
  ## - include: smartmontools.yml # only on non-virtual server
  # - include: mysql.yml # TODO: fix automysqlbackup & mysqloptimize
  # - include: redis.yml
  # - include: geoip.yml
  - include: nginx.yml
  # - include: puma.yml

  handlers:
  - name: Restart ssh
    action: service name=ssh state=restarted