---
- name: Install basics
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: true
  sudo: yes
  with_items:
    - build-essential
    - gzip
    - ipset
    - clamav
    - clamav-freshclam
    - clamav-docs
    - iftop
    - ntp
    - git
    - subversion
    - acpid
    - libnotify-bin
    - apt-file
    - update-notifier-common
    - unattended-upgrades
    - mosh
    - apt-listchanges
    - zip
    - htop
    - imagemagick
    - apticron
    - curl
    - gawk
    - landscape-common
    # - autoconf
    # - automake
    # - bison
    # - libxml2-dev
    # - libffi-dev
    # - libyaml-dev
    # - libssl-dev
    # - libsqlite3-dev
    # - libgdbm-dev
    # - libncurses5-dev
    # - libreadline6-dev
    # - libtool
    # - libyaml-dev
    # - nfs-common # make virtualbox faster
    # - pkg-config
    # - sqlite3
    # - vim
    # - zlib1g-dev

- name: Copy apticron config
  copy:
    src: ../etc/apticron/apticron.conf
    dest: /etc/apticron/apticron.conf
    owner: root
    group: root
    mode: '0644'
  sudo: yes

- name: Copy unattended-upgrades config
  copy:
    src: ../etc/apt/apt.conf.d/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
  sudo: yes

- name: Enable unattended-upgrades
  lineinfile:
    state: present
    create: yes
    dest: /etc/apt/apt.conf.d/10periodic
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  sudo: yes
  with_items:
    - { line: 'APT::Periodic::Update-Package-Lists "1";', regexp: "^APT::Periodic::Update-Package-Lists" }
    - { line: 'APT::Periodic::Unattended-Upgrade "1";', regexp: "^APT::Periodic::Unattended-Upgrade" }
    - { line: 'APT::Periodic::Enable "1";', regexp: "^APT::Periodic::Enable"}
    - { line: 'APT::Periodic::Download-Upgradeable-Packages "1";', regexp: "^APT::Periodic::Download-Upgradeable-Packages"}
    - { line: 'APT::Periodic::Verbose "2";', regexp: "^APT::Periodic::Verbose" }
    - { line: 'APT::Periodic::AutocleanInterval "28";', regexp: "^APT::Periodic::AutocleanInterval"}

- name: Update apt-file
  shell: "apt-file update"
  sudo: yes

- name: Copy update-notifier config
  copy:
    src: ../usr/lib/update-notifier/update-motd-reboot-required
    dest: /usr/lib/update-notifier/update-motd-reboot-required
    owner: root
    group: root
    mode: '0755'
  sudo: yes
