---
- name: Add SSL group
  group:
    name: ssl
    state: present
  sudo: yes
  tags: ssl

- name: Add local user to SSL group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: ssl
    append: yes
  sudo: yes
  tags: ssl

- name: Add SSL certs directory
  file:
    path: /etc/ssl/localcerts/
    state: directory
    owner: root
    group: ssl
    mode: 0755
  sudo: yes
  tags: ssl

- name: Add SSL certs
  copy:
    src: "{{item}}"
    dest: /etc/ssl/localcerts/
    owner: root
    group: ssl
    mode: 0440
  tags: ssl
  sudo: yes
  with_fileglob:
    - ~/myl_sensitive/localcerts/*.pem
    - ~/myl_sensitive/localcerts/*.der
    - ~/myl_sensitive/localcerts/*.key
    - ~/myl_sensitive/localcerts/*.key_with_rsa
    - ~/myl_sensitive/localcerts/*.conf
    - ~/myl_sensitive/localcerts/*.csr
    - ~/myl_sensitive/localcerts/*.txt

- name: Add CRT files
  copy:
    src: "{{item}}"
    dest: /etc/ssl/localcerts/
    owner: root
    group: ssl
    mode: 0444
  tags: ssl
  sudo: yes
  with_fileglob:
    - ~/myl_sensitive/localcerts/*.crt

- name: Make monit cert no more than 0700
  file:
    path: /etc/ssl/localcerts/monit.pem
    mode: 0400
  tags: ssl
  sudo: yes

- name: Symlink current certs
  file:
    dest: "/etc/ssl/localcerts/{{ item.dest }}"
    src: "/etc/ssl/localcerts/{{ item.src }}"
    state: link
    owner: root
    group: ssl
  sudo: yes
  with_items:
    - { dest: "makeyourlaws.org.combined.crt", src: "makeyourlaws.org.ev.combined.2014.crt" }
    - { dest: "makeyourlaws.org.combined.pem", src: "makeyourlaws.org.ev.combined.2014.crt" }
    - { dest: "makeyourlaws.org.crt", src: "makeyourlaws.org.ev.2014.crt" }
    - { dest: "makeyourlaws.org.csr", src: "makeyourlaws.org.ev.2014.csr" }
    - { dest: "makeyourlaws.org.key", src: "makeyourlaws.org.ev.2014.key_with_rsa" }
    - { dest: "makeyourlaws.org.key_with_rsa", src: "makeyourlaws.org.ev.2014.key_with_rsa" }
