---
- name: Install exim4 and mutt
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
    - exim4
    - sasl2-bin
    - opendkim
    - opendkim-tools
    - swaks
    - mutt
  sudo: yes
  tags: mail

- name: Make exim group
  group:
    name: Debian-exim
    system: yes
    state: present
  sudo: yes
  tags: mail

- name: Create exim user
  user:
    name: Debian-exim
    groups: "sasl,ssl"
    group: Debian-exim
    shell: /bin/false
    state: present
    system: yes
  sudo: yes
  tags: mail

- name: Set mailname
  template:
    src: ../etc/mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  sudo: yes
  tags: mail

- name: Set root mailing aliases
  copy:
    src: ../etc/aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  sudo: yes

- name: Add exim4 config
  copy:
    src: "../etc/exim4/{{item}}"
    dest: "/etc/exim4/{{item}}"
    owner: root
    group: root
    mode: 0644
  tags: mail
  sudo: yes
  with_items:
    - conf.d/main/00_localmacros
    - conf.d/main/01_exim4-config_listmacrosdefs
    - conf.d/main/02_exim4-config_options
    - conf.d/main/03_exim4-config_tlsoptions
    - conf.d/router/200_exim4-config_primary
    - conf.d/router/500_exim4-config_hubuser

- name: Add custom exim4 config
  template:
    src: ../etc/exim4/update-exim4.conf.conf.j2
    dest: /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode: 0644
  tags: mail
  sudo: yes

- name: Add mutt config
  copy:
    src: ../etc/Muttrc
    dest: /etc/Muttrc
    owner: root
    group: root
    mode: 0644
  tags: mail
  sudo: yes

- name: Add root mutt config
  copy:
    src: ../root/.muttrc
    dest: /root/.muttrc
    owner: root
    group: root
    mode: 0640
  tags: mail
  sudo: yes

- name: Add saslauthd default
  copy:
    src: "..{{item}}"
    dest: "{{item}}"
    owner: root
    group: root
    mode: 0644
  tags: mail
  sudo: yes
  with_items:
    - /etc/opendkim.conf
    - /etc/default/saslauthd

- name: Add exim4 certs
  copy:
    src: "{{item}}"
    dest: /etc/exim4/
    owner: root
    group: Debian-exim
    mode: 0440
  tags: mail
  sudo: yes
  with_fileglob:
    - ~/myl_sensitive/server/etc/exim4/*.key

- name: Add exim4 users
  copy:
    src: ~/myl_sensitive/server/etc/exim4/passwd
    dest: /etc/exim4/passwd
    owner: root
    group: Debian-exim
    mode: 0640
  tags: mail
  sudo: yes

- name: Make /etc/mail dir
  file:
    path: "/etc/mail/"
    state: directory
    owner: root
    group: root
    mode: 0755
  sudo: yes
  tags: mail

# - name: Make exim dirs properly owned
#   file:
#     path: "{{ item }}"
#     state: directory
#     recurse: yes
#     owner: Debian-exim
#     group: Debian-exim
#     mode: 0751
#   sudo: yes
#   tags: mail
#   with_items:
#     - /etc/exim4
#     - /var/lib/exim4

- name: Symlink dkim key
  file:
    src: "/etc/exim4/narn.dkim.private.key"
    dest: "/etc/mail/dkim.key"
    state: link
    owner: root
    group: root
  sudo: yes
  tags: mail

- name: Run update-exim4.conf
  shell: "update-exim4.conf"
  sudo: yes
  tags: mail

- name: Restart sasl
  service:
    name: saslauthd
    state: restarted
  sudo: yes
  tags: mail

- name: Restart exim
  service:
    name: exim4
    state: restarted
  sudo: yes
  tags: mail