---
- name: Update hostname
  hostname: "name={{inventory_hostname}}"
  sudo: yes

- name: Ensure hostname in /etc/hosts
  lineinfile:
    state: present
    create: yes
    dest: /etc/hosts
    line: "{{ansible_eth0.ipv4.address}} {{inventory_hostname}}.makeyourlaws.org {{inventory_hostname}}"
    regexp: "^.*{{inventory_hostname}}$"
  sudo: yes

- name: Set locales
  copy:
    src: ../etc/default/locale
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
  sudo: yes

- name: Set root mailing aliases
  copy:
    src: ../etc/aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  sudo: yes

- name: Disable IPv6
  lineinfile:
    state: present
    create: yes
    dest: /etc/sysctl.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  sudo: yes
  with_items:
    - { line: "net.ipv6.conf.all.disable_ipv6 = 1", regexp: "^net.ipv6.conf.all.disable_ipv6" }
    - { line: "net.ipv6.conf.default.disable_ipv6 = 1", regexp: "^net.ipv6.conf.default.disable_ipv6" }
    - { line: "net.ipv6.conf.lo.disable_ipv6 = 1", regexp: "^net.ipv6.conf.lo.disable_ipv6" }

- name: Reboot on out of memory
  lineinfile:
    state: present
    create: yes
    dest: /etc/sysctl.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  sudo: yes
  with_items:
    - { line: "vm.panic_on_oom = 1", regexp: "^vm.panic_on_oom" }
    - { line: "kernel.panic = 10", regexp: "^kernel.panic" }

- name: Set network interfaces
  template:
    dest: /etc/network/interfaces
    src: ../etc/network/interfaces.j2
    owner: root
    group: root
    mode: 0644
  sudo: yes

- name: Check if both IPs are up
  shell: "ifconfig  | grep  '{{private_ip}}' && ifconfig | grep '{{public_ip}}' && echo 'yes' || echo 'no'"
  register: interfaces_set

- name: Restart network interface
  shell: "ifdown -a && ifup -a"
  sudo: yes
  when: '"no" in interfaces_set.stdout'


- name: Remove DHCP
  apt:
    pkg: "{{ item }}"
    state: absent
  sudo: yes
  with_items:
    - isc-dhcp-client
    - dhcp3-client
    - dhcpcd

