---
- name: Update hostname
  hostname:
    name: "{{inventory_hostname}}"
  sudo: yes

- name: Ensure hostname in /etc/hosts
  lineinfile:
    state: present
    create: yes
    dest: /etc/hosts
    line: "{{ansible_eth0.ipv4.address}} {{inventory_hostname}}.makeyourlaws.org {{inventory_hostname}}"
    regexp: "^.*{{inventory_hostname}}$"
  sudo: yes

- name: Set locales
  copy:
    src: ../etc/default/locale
    dest: /etc/default/locale
    owner: root
    group: root
    mode: '0644'
  sudo: yes

- name: Reboot on out of memory
  sysctl:
    state: present
    reload: yes
    sysctl_set: yes
    name: "{{ item.line }}"
    value: "{{ item.value }}"
  sudo: yes
  with_items:
    - { line: "vm.panic_on_oom", value: "1" }
    - { line: "kernel.panic", value: "10" }

- name: Set network interfaces
  template:
    dest: /etc/network/interfaces
    src: ../etc/network/interfaces.j2
    owner: root
    group: root
    mode: '0644'
  sudo: yes

- name: Check if both IPs are up
  shell: "ifconfig  | grep  '{{private_ip}}' && ifconfig | grep '{{public_ip}}' && echo 'yes' || echo 'no'"
  register: interfaces_set

- name: Restart network interface
  shell: "ifdown -a && ifup -a"
  sudo: yes
  when: '"no" in interfaces_set.stdout'


- name: Remove DHCP
  apt:
    pkg: "{{ item }}"
    state: absent
  sudo: yes
  with_items:
    - isc-dhcp-client
    - dhcp3-client
    - dhcpcd
