---
- name: Install monit
  apt:
    pkg: monit
    state: latest
  sudo: yes
  tags: monit

- name: Add monitrc
  copy:
    src: ../etc/monit/monitrc
    dest: /etc/monit/monitrc
    owner: root
    group: root
    mode: 0600
  tags: monit
  sudo: yes

- name: Add monitrc.d conf files
  copy:
    src: "{{item}}"
    dest: /etc/monit/monitrc.d/
    owner: root
    group: root
    mode: 0644
  tags: monit
  sudo: yes
  with_fileglob:
    - ../etc/monit/monitrc.d/*

- name: Add ufw check file
  copy:
    src: ../etc/monit/ufw_check.sh
    dest: /etc/monit/ufw_check.sh
    owner: root
    group: root
    mode: 0754
  tags: monit
  sudo: yes

- name: Symlink system monits
  file:
    src: "/etc/monit/monitrc.d/{{item}}"
    dest: "/etc/monit/conf.d/{{item}}"
    state: link
    owner: root
    group: root
  with_items:
    - cron
    - system
    - fs
    # - mdadm
    - ntp
    - openssh-server
    # - pdns-recursor
    # - postfix
    # - snmpd
  sudo: yes

- name: Symlink post-Precise system monits
  file:
    src: "/etc/monit/monitrc.d/{{item}}"
    dest: "/etc/monit/conf.d/{{item}}"
    state: link
    owner: root
    group: root
  sudo: yes
  with_items:
    - atd
    - acpid
    - rsyslog
  when: ansible_distribution_release != 'precise'

- name: Reload monit
  service:
    name: monit
    state: reloaded
  sudo: yes