---
- name: "Create mylfrontend user"
  user:
    name: mylfrontend
    shell: "/bin/bash"
    groups: "makeyourlaws,users,rvm"
    password: "{{ lookup('file', '~/myl_sensitive/server/mylfrontend_mylfrontend_password_crypted.txt') }}"
    state: present
  sudo: yes

- name: "Add authorized_key for mylfrontend user"
  authorized_key:
    user: "mylfrontend"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  sudo: yes

- name: Add MYL frontend init.d files
  copy:
    src: "{{item}}"
    dest: /etc/init.d/
    owner: root
    group: root
    mode: 0644
  tags: mylfrontend
  sudo: yes
  with_fileglob:
    - ../etc/init.d/mylfrontend_*

- name: Add MYL frontend puma conf
  lineinfile:
    state: present
    create: yes
    dest: /etc/puma.conf
    line: "/home/makeyourlaws/makeyourlaws.org/current,makeyourlaws,/home/makeyourlaws/makeyourlaws.org/current/config/puma/production.rb"
    regexp: "^/home/makeyourlaws/makeyourlaws.org"
    owner: root
    group: root
    mode: 0644
  sudo: yes
  tags: mylfrontend

- name: Enable MYL frontend
  file:
    src: "/etc/nginx/sites-available/{{item}}.conf"
    dest: "/etc/nginx/sites-enabled/{{item}}.conf"
    state: link
    owner: root
    group: root
    mode: 0644
  tags: mylfrontend
  sudo: yes
  with_items:
    - mylfrontend_tor
    - mylfrontend
    # - mylwiki

- name: Symlink mylfrontend_puma monit files
  file:
    src: "/etc/monit/monitrc.d/{{item}}"
    dest: "/etc/monit/conf.d/{{item}}"
    state: link
    owner: root
    group: root
  sudo: yes
  tags: mylfrontend
  with_items:
    - mylfrontend_resque
    - mylfrontend_resque_scheduler
    - mylfrontend_puma

- name: Reload monit
  service:
    name: monit
    state: reloaded
  sudo: yes
  tags: mylfrontend

- name: Add myl_production DB
  mysql_db:
    name: myl_production
    state: present
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  sudo: yes

- name: Add mysql user
  mysql_user:
    user: myl_production
    host: "127.0.0.1"
    password: "{{ lookup('file', '~/myl_sensitive/keys/database.production') }}"
    priv: "myl_production:ALL"
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  sudo: yes
  tags: mylfrontend
