---
- name: Install mysql
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
    - libmysqlclient-dev
    - automysqlbackup
  sudo: yes

- name: Make mysql group
  group:
    name: mysql
    system: yes
    state: present
  sudo: yes

- name: Add my.cnf
  copy:
    src: ../etc/mysql/my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    group: mysql
    mode: '0600'
  tags: mysql
  sudo: yes

- name: Add tuning script
  copy:
    src: ../etc/mysql/tuning.sh
    dest: /etc/mysql/tuning.sh
    owner: root
    group: mysql
    mode: '0700'
  tags: mysql
  sudo: yes

- name: Add mysql user to SSL group
  user:
    name: mysql
    groups: ssl
    append: yes
  sudo: yes
  tags: mysql

- name: Delete logfiles to fix innodb different size issue
  file:
    dest: "{{item}}"
    state: absent
  sudo: yes
  tags: mysql
  with_items:
    - /var/lib/mysql/ib_logfile0
    - /var/lib/mysql/ib_logfile1

- name: Start the MySQL service
  service:
    name: mysql
    state: started
  sudo: yes

- name: Remove ipv6 and hostname root user
  mysql_user:
    user: 'root'
    host: "{{item}}"
    state: absent
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  sudo: yes
  with_items:
    - '::1'
    - '{{inventory_hostname}}'

- name: Update mysql root password
  mysql_user:
    name: root
    host: "{{item}}"
    password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  with_items:
    - 127.0.0.1
    - localhost
  sudo: yes

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  sudo: yes

- name: Ensure anonymous users are not in the database
  mysql_user:
    user: ''
    # host: "{{item}}"
    state: absent
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  # with_items:
  #   - 127.0.0.1
  #   - '::1'
  #   - localhost
  #   - '{{inventory_hostname}}'
  sudo: yes

- name: Lock down mysql executables
  file:
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: mysql
    mode: '0750'
  sudo: yes
  with_items:
    - mysqladmin
    - mysqlaccess
    - mysqlbinlog
    - mysqlbug
    - mysqlcheck
    - mysql_client_test
    # - mysql_config
    - mysql_convert_table_format
    - mysqldump
    - mysqldumpslow
    - mysqld_multi
    - mysqld_safe
    - mysql_find_rows
    - mysql_fix_extensions
    - mysqlhotcopy
    - mysql_install_db
    - mysql_plugin
    - mysqlreport
    - mysql_secure_installation
    - mysql_setpermission
    - mysqlshow
    - mysqlslap
    - mysqltest
    - mysql_tzinfo_to_sql
    - mysql_upgrade
    - mysql_waitpid
    - mysql_zap

- name: Add local user and debian-sys-maint to mysql group
  user:
    name: "{{ item }}"
    groups: mysql
    append: yes
  sudo: yes
  with_items:
    - debian-sys-maint
    - "{{ lookup('env', 'USER') }}"

- name: Add optimize user
  mysql_user:
    user: 'optimize'
    priv: '*.*:SELECT,INSERT'
    host: "{{item}}"
    password: "{{ lookup('file', '~/myl_sensitive/server/database_optimize.production') }}"
    state: present
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  with_items:
    - 127.0.0.1
    - localhost
  sudo: yes

- name: Add backup user
  mysql_user:
    user: 'backup'
    priv: "*.*:SELECT,RELOAD,LOCK TABLES"
    host: "{{item}}"
    password: "{{ lookup('file', '~/myl_sensitive/server/database_backup.production') }}"
    state: present
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  with_items:
    - 127.0.0.1
    - localhost
  sudo: yes

- name: Add root my.cnf for backup and optimize
  template:
    src: ../etc/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: mysql
    mode: '0600'
  sudo: yes

- name: Add automysqlbackup folder
  file:
    path: /root/automysqlbackup
    owner: root
    group: mysql
    mode: '0600'
    state: directory
  sudo: yes

- name: Add automysqlbackup conf
  copy:
    src: ../etc/default/automysqlbackup
    dest: /etc/default/automysqlbackup
    owner: root
    group: mysql
    mode: '0644'
  sudo: yes

# - name: Add mysql daily backup
#   copy:
#     src: ../etc/cron.daily/automysqlbackup
#     dest: /etc/cron.daily/automysqlbackup
#     owner: root
#     group: root
#     mode: '0755'
#   sudo: yes

# - name: Add mysql weekly optimize
#   copy:
#     src: ../etc/cron.weekly/mysqloptimize
#     dest: /etc/cron.weekly/mysqloptimize
#     owner: root
#     group: root
#     mode: '0755'
#   sudo: yes

# TODO: only if new install
- name: Delete logfiles to fix innodb different size issue
  file:
    dest: "{{item}}"
    state: absent
  sudo: yes
  tags: mysql
  with_items:
    - /var/lib/mysql/ib_logfile0
    - /var/lib/mysql/ib_logfile1

# TODO: Only if my.cnf, root p/w, test db, or anon users have changed
- name: Restart the MySQL service
  service:
    name: mysql
    state: restarted
  sudo: yes

- name: Symlink mysql monit
  file:
    src: /etc/monit/monitrc.d/mysql
    dest: /etc/monit/conf.d/mysql
    state: link
    owner: root
    group: root
  sudo: yes
  tags: mysql

- name: Reload monit
  service:
    name: monit
    state: reloaded
  sudo: yes
  tags: mysql