---
- name: Install mysql
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
    - libmysqlclient-dev
  sudo: yes

- name: Add my.cnf
  copy:
    src: ../etc/mysql/my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0600
  tags: mysql
  sudo: yes

- name: Start the MySQL service
  service:
    name: mysql
    state: started
  sudo: yes

- name: Update mysql root password
  mysql_user:
    name: root
    host: "{{item}}"
    password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  sudo: yes

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  sudo: yes

- name: Ensure anonymous users are not in the database
  mysql_user:
    user: ''
    host: "{{item}}"
    state: absent
    login_user: root
    login_password: "{{ lookup('file', '~/myl_sensitive/server/mysql_root_password.txt') }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  sudo: yes

- name: Restart the MySQL service
  service:
    name: mysql
    state: restarted
  sudo: yes

- name: Symlink mysql monit
  file:
    src: /etc/monit/monitrc.d/mysql
    dest: /etc/monit/conf.d/mysql
    state: link
    owner: root
    group: root
  sudo: yes
  tags: mysql

- name: Reload monit
  service:
    name: monit
    state: reloaded
  sudo: yes
  tags: mysql