---
- name: Lock down sysctl networking
  sysctl:
    state: present
    reload: yes
    sysctl_set: yes
    name: "{{ item.line }}"
    value: "{{ item.value }}"
  sudo: yes
  with_items:
    # Disable IPv6
    - { line: "net.ipv6.conf.all.disable_ipv6", value: "1" }
    - { line: "net.ipv6.conf.default.disable_ipv6", value: "1" }
    - { line: "net.ipv6.conf.lo.disable_ipv6", value: "1" }
    # IP Spoofing protection
    - { line: "net.ipv4.conf.all.rp_filter", value: "1" }
    - { line: "net.ipv4.conf.default.rp_filter", value: "1" }
    # Ignore ICMP
    - { line: "net.ipv4.icmp_echo_ignore_broadcasts", value: "1" }
    # - { line: "net.ipv4.icmp_echo_ignore_all = 1", regexp: "^[# ]*net.ipv4.icmp_echo_ignore_all" }
    # Disable source packet routing
    - { line: "net.ipv4.conf.all.accept_source_route", value: "0" }
    - { line: "net.ipv6.conf.all.accept_source_route", value: "0" }
    - { line: "net.ipv4.conf.default.accept_source_route", value: "0" }
    - { line: "net.ipv6.conf.all.accept_source_route", value: "0" }
    - { line: "net.ipv6.conf.default.accept_source_route", value: "0" }
    # Log Martians
    - { line: "net.ipv4.conf.all.log_martians", value: "1" }
    - { line: "net.ipv4.icmp_ignore_bogus_error_responses", value: "1" }
    - { line: "net.ipv4.conf.all.rp_filter", value: "1" }
    # Ignore send redirects
    - { line: "net.ipv4.conf.all.send_redirects", value: "0" }
    - { line: "net.ipv4.conf.default.send_redirects", value: "1" }
    # Block SYN attacks
    - { line: "net.ipv4.tcp_syncookies", value: "1" }
    - { line: "net.ipv4.tcp_max_syn_backlog", value: "2048" }
    - { line: "net.ipv4.tcp_synack_retries", value: "2" }
    - { line: "net.ipv4.tcp_syn_retries", value: "5" }
    # Ignore ICMP redirects
    - { line: "net.ipv4.conf.all.accept_redirects", value: "0" }
    - { line: "net.ipv6.conf.all.accept_redirects", value: "0" }
    - { line: "net.ipv4.conf.default.accept_redirects", value: "0" }
    - { line: "net.ipv6.conf.default.accept_redirects", value: "0" }

- name: Add ip spoofing protection in host.conf
  lineinfile:
    state: present
    create: yes
    dest: /etc/host.conf
    line: nospoof on
    regexp: "^nospoof"
  sudo: yes
