- name: Check if nginx signing key exists
  shell: "apt-key list | grep nginx && echo 'yes' || echo 'no'"
  register: nginx_signing_key
  sudo: yes
  tags: nginx

- name: Add nginx signing key
  shell: "curl http://nginx.org/keys/nginx_signing.key | apt-key add -"
  when: '"no" in nginx_signing_key.stdout'
  sudo: yes
  tags: nginx

- name: Make nginx group
  group:
    name: nginx
    system: yes
    state: present
  sudo: yes

- name: Make nginx user
  user:
    name: nginx
    createhome: no
    groups: ssl
    group: nginx
    shell: /bin/false
    system: yes
    state: present
  sudo: yes

- name: Add nginx.list
  template:
    src: ../etc/apt/sources.list.d/nginx.list.j2
    dest: /etc/apt/sources.list.d/nginx.list
    owner: root
    group: root
    mode: '0644'
  tags: nginx
  sudo: yes

- name: Add nginx directories
  file:
    path: "{{ item }}"
    owner: nginx
    group: nginx
    state: directory
    mode: '0750'
  tags: nginx
  sudo: yes
  with_items:
    - /etc/nginx/
    - /var/log/nginx/

- name: Install mod_pagespeed prereqs
  apt:
    pkg: "{{ item }}"
    state: latest
  sudo: yes
  with_items:
    - build-essential
    - zlib1g-dev
    - libpcre3
    - libpcre3-dev
    - unzip
    - libpcrecpp0
    - libssl-dev
    - zlib1g-dev


# - name: Uninstall nginx
#   apt:
#     pkg: nginx
#     state: absent
#   sudo: yes


- name: Add build_nginx.sh
  copy:
    src: ../root/build_nginx.sh
    dest: /root/build_nginx.sh
    owner: root
    group: root
    mode: '0700'
  tags: nginx
  sudo: yes

- name: Install nginx
  shell: "/root/build_nginx.sh"
  tags: nginx
  sudo: yes

# - name: Install nginx
#   apt:
#     pkg: nginx
#     state: latest
#   sudo: yes

- name: Add nginx.conf
  copy:
    src: ../etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  tags: nginx
  sudo: yes

- name: Remove the default app
  shell: "rm /etc/nginx/conf.d/default.conf 2> /dev/null || echo 1" # ignore if not there
  sudo: yes

- name: Add site directories
  file:
    path: "/etc/nginx/{{item}}"
    state: directory
  with_items:
    - sites-available
    - sites-enabled
  tags: nginx
  sudo: yes

- name: Symlink nginx monit
  file:
    src: /etc/monit/monitrc.d/nginx
    dest: /etc/monit/conf.d/nginx
    state: link
    owner: root
    group: root
  sudo: yes
  tags: nginx

- name: Reload monit
  service:
    name: monit
    state: reloaded
  sudo: yes
  tags: nginx