- name: Add run-puma and ctl-puma
  copy:
    src: ../usr/local/bin/{{item}}
    dest: /usr/local/bin/{{item}}
    owner: root
    group: root
    mode: '0755'
  tags: puma
  sudo: yes
  with_items:
    - run-puma
    - ctl-puma

- name: Add puma init.d
  copy:
    src: ../etc/init.d/puma
    dest: /etc/init.d/puma
    owner: root
    group: root
    mode: '0755'
  tags: puma
  sudo: yes

- name: Install puma init.d
  shell: update-rc.d puma defaults
  sudo: yes
  tags: puma

- name: Symlink puma monit
  file:
    src: /etc/monit/monitrc.d/puma
    dest: /etc/monit/conf.d/puma
    state: link
    owner: root
    group: root
  sudo: yes
  tags: puma

- name: Reload monit
  service:
    name: monit
    state: reloaded
  sudo: yes
  tags: puma