---
- name: Install prereq packages
  apt:
    pkg: "{{ item }}"
    state: latest
  sudo: yes
  with_items:
    - autoconf
    - automake
    - autotools-dev
    - libtool
    - pkg-config
    - zlib1g-dev
    - libcunit1-dev
    - libssl-dev
    - libxml2-dev
    - libevent-dev
    - libevent-openssl-2.0-5
    - libxml2
    - pkg-config
    - zlibc
    - libcunit1
    - OpenSSL

