#!/bin/sh -e
#
# helper for update-motd

if [ -f /var/run/reboot-required ]; then
        cat /var/run/reboot-required
fi

if [ -f /var/run/reboot-required.pkgs ]; then
        cat /var/run/reboot-required.pkgs
fi