#!/bin/bash

#Check if removed-but-not-purged
test -x /usr/share/logwatch/scripts/logwatch.pl || exit 0

#execute
# /usr/sbin/logwatch --output mail

/usr/sbin/logwatch --output mail --mailto debug+logwatch.daily@makeyourlaws.org --detail high --format html --range 'between -1 days and today'
